composers/urls.py
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'composers'
urlpatterns = [
    path('', views.index, name='composers')
]

home/urls.py
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'home'
urlpatterns = [
    path('', views.index, name='home')
]

register/urls.py
from tkinter import N
from . import views
from django.urls import include, path
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
app_name = 'register'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('private/', views.private.as_view(), name='private'),
    path('song/', views.private_song.as_view(), name='private_song'),
    path('composer/', views.private_composer.as_view(), name='private_composer'),
    path('singer/', views.private_singer.as_view(), name='private_singer'),
    path('add_composer/', views.add_composer, name='add_composer'),
    path('add_singer/', views.add_singer, name='add_singer'),
    path('add_song/', views.add_song, name='add_song'),
    #path('forgetpassword/', views.forgetpassword(), name='forgetpassword')
    path('change_user/', views.change_user, name='change_user'),
    path('newpassword/', auth_views.PasswordChangeView.as_view(template_name='register/newpassword.html',success_url='login'), name = 'newpassword'),
    path('newpassword/login/', views.login_user, name='newpassword_success'),
    path('delete_song/<event_id>',views.delete_song,name='delete_song'),
    path('delete_singer/<event_id>',views.delete_singer,name='delete_singer'),
    path('delete_composer/<event_id>',views.delete_composer,name='delete_composer'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

singers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'singers'
urlpatterns = [
    path('', views.index, name='singers'),
]

songs/urls.py
from django.conf.urls.static import static
from tkinter import N

from django.conf import settings
from . import views
from django.urls import include, path
app_name = 'songs'
urlpatterns = [
    path('', views.index, name='songs')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webmusic/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('composers/', include('composers.urls')),
    path('singers/', include('singers.urls')),
    path('songs/', include('songs.urls')),
    path('register/', include('register.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

singers/models.py
from django.db import models

# Create your models here.

singers/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.core.paginator import Paginator
from register.models import Upload_Singer

# Create your views here.
def index(request):
    upload_singer = Upload_Singer.objects.all() 
    return render(request, 'singers/singers.html', {'upload_singer': upload_singer})

singers/templates/singers/onesinger.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Entro</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'home/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout contineer_page">
  <!-- header -->
  <header>
    <!-- header inner -->

      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9">
              
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li > <a href="{% url 'home:home' %}">Home</a> </li>
                  
                      <li> <a href="{% url 'songs:songs' %}">bài hát</a> </li>
                      <li class="active"> <a href="{% url 'singers:singers' %}">ca sĩ </a> </li>
                      <li > <a href="{% url 'composers:composers' %}">nhạc sĩ</a> </li>
      
                        <li > <a   href="{% url 'register:login' %}">đăng nhập</a> </li>
                        <li > <a   href="{% url 'register:register' %}">đăng ký</a> </li>
                      <li  > <a  class="last_manu" href="#"><img src="{% static 'home/images/search_icon.png' %}" alt="#" /></a> </li>
                      
                     </ul>
                   </nav>
                
               </div> 
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
   
</header>

<div class="backgro_mh">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heding">
          
        </div>
      </div>
    </div>
  </div>
</div>


          <!-- Javascript files-->
          <script src="{% static 'home/js/jquery.min.js' %}"></script>
          <script src="{% static 'home/js/popper.min.js' %}"></script>
          <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'home/js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'home/js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'home/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'home/js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>




</body>

</html>

singers/templates/singers/singers.html
<!DOCTYPE html>
<html lang="en">

<head>
  <style>
    .column {
  float: center;
  width: 100%;
  padding: 50px;
  height: 50px;
    }
    img{
      max-width: 250px;
      max-height:250px;

    }
  </style>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Entro</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'home/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout contineer_page">
  <!-- header -->
  <header>
    <!-- header inner -->
      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col logo_section">
              <div class="full">
                <div class="center-desk">
                </div>
              </div>
            </div>
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9">
              
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li > <a href="{% url 'home:home' %}">Home</a> </li>
                  
                      <li> <a href="{% url 'songs:songs' %}">bài hát</a> </li>
                      <li class="active"> <a href="{% url 'singers:singers' %}">ca sĩ </a> </li>
                      <li > <a href="{% url 'composers:composers' %}">nhạc sĩ</a> </li>
      
                        <li > <a   href="{% url 'register:login' %}">đăng nhập</a> </li>
                        <li > <a   href="{% url 'register:register' %}">đăng ký</a> </li>
                      <li  > <a  class="last_manu" href="#"><img src="{% static 'home/images/search_icon.png' %}" alt="#" /></a> </li>
                      
                     </ul>
                   </nav>
                
               </div> 
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     
</header>


<div class="backgro_mh">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <div class="heding">
           <h2> CA SĨ</h2>
        </div>
      </div>
        
    </div>
  </div>
</div>

<!-- upcoming -->
<div id="singers" class="upcoming">
  <div class="container-fluid padding_left3">
    <div class="row display_boxflex">
      <div class="col-xl-5 col-lg-5 col-md-5 col-sm-12">
        {% for item in upload_singer %}
          <div>
          
          <h3>  Tên : {{item.name}}  </h3></div>
          <p> tên thật: {{item.real_name}}</p>
          <p>Mô tả : {{item.details}} </p><p> <img src="{{item.image.url}}" alt="" width="50%" height="50%"> </p>
          {% endfor %}
      </div> 
      <div class="col-xl-7 col-lg-7 col-md-7 col-sm-12 border_right">
      </div>
    </div>
  </div>
</div>
<!-- end upcoming -->

          <!-- Javascript files-->
          <script src="{% static 'home/js/jquery.min.js' %}"></script>
          <script src="{% static 'home/js/popper.min.js' %}"></script>
          <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'home/js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'home/js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'home/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'home/js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>



</body>

</html>