composers/urls.py
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'composers'
urlpatterns = [
    path('', views.index, name='composers')
]

home/urls.py
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'home'
urlpatterns = [
    path('', views.index, name='home')
]

register/urls.py
from tkinter import N
from . import views
from django.urls import include, path
from django.conf import settings
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
app_name = 'register'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_user, name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('private/', views.private.as_view(), name='private'),
    path('song/', views.private_song.as_view(), name='private_song'),
    path('composer/', views.private_composer.as_view(), name='private_composer'),
    path('singer/', views.private_singer.as_view(), name='private_singer'),
    path('add_composer/', views.add_composer, name='add_composer'),
    path('add_singer/', views.add_singer, name='add_singer'),
    path('add_song/', views.add_song, name='add_song'),
    #path('forgetpassword/', views.forgetpassword(), name='forgetpassword')
    path('change_user/', views.change_user, name='change_user'),
    path('newpassword/', auth_views.PasswordChangeView.as_view(template_name='register/newpassword.html',success_url='login'), name = 'newpassword'),
    path('newpassword/login/', views.login_user, name='newpassword_success'),
    path('delete_song/<event_id>',views.delete_song,name='delete_song'),
    path('delete_singer/<event_id>',views.delete_singer,name='delete_singer'),
    path('delete_composer/<event_id>',views.delete_composer,name='delete_composer'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

singers/urls.py
from django.conf import settings
from django.conf.urls.static import static
from tkinter import N
from . import views
from django.urls import include, path
app_name = 'singers'
urlpatterns = [
    path('', views.index, name='singers'),
]

songs/urls.py
from django.conf.urls.static import static
from tkinter import N

from django.conf import settings
from . import views
from django.urls import include, path
app_name = 'songs'
urlpatterns = [
    path('', views.index, name='songs')
]+ static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webmusic/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('composers/', include('composers.urls')),
    path('singers/', include('singers.urls')),
    path('songs/', include('songs.urls')),
    path('register/', include('register.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

register/models.py
from django import forms
from django.db import models
from matplotlib import image, widgets
from numpy import real
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()
# Create your models here.


class Users(models.Model):
    id = models.IntegerField(primary_key=True)
    username = models.CharField(max_length=15)
    password = models.CharField(max_length=30)
    name = models.TextField()
    birthday = models.DateField()
    details = models.TextField()

    def __str__(self):
        return self.username
def media_path(instance,filename):
    return '/'.join(['content',instance.user.id, filename])
class Upload_Singer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    real_name = models.CharField(max_length=255,null=True)
    image = models.ImageField(null=True,upload_to='media/')
    details = models.CharField(max_length=255,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
        
class Upload_Composer(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    real_name = models.CharField(max_length=255,null=True)
    image = models.ImageField(blank=True,upload_to='media/')
    details = models.CharField(max_length=255,null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    def __str__(self):
        return self.name

class Upload_Songs(models.Model):    
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255)
    file = models.FileField(blank=True)
    singer = models.ForeignKey("Upload_Singer", on_delete=models.CASCADE)  
    composer = models.ForeignKey("Upload_Composer", on_delete=models.CASCADE)   
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    details = models.CharField(max_length=255,null=True)
    
    def __str__(self):
        return self.name

register/forms.py
from dataclasses import field, fields
from pyexpat import model
import django
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Upload_Composer, Upload_Singer, Upload_Songs
from django import forms


class register_Form(UserCreationForm):
    class Meta:
        model = User
        fields =['username','password1','password2','last_name','first_name','email']

class changeUser_Form(ModelForm):
    class Meta:
        model = User
        fields =['username','last_name','first_name','email']

class addsong_Form(ModelForm):
    class Meta:
        model = Upload_Songs
        fields =['name','file','singer','composer','details']

class addcomposer_Form(ModelForm):
    class Meta:
        model = Upload_Composer
        fields =['name','real_name','image','details']

class addsinger_Form(ModelForm):
    class Meta:
        model = Upload_Singer
        fields =['name','real_name','image','details']



    

register/views.py
import email
from random import randint
from pathlib import Path
from django.core.files import File
from click import password_option
from django.http import HttpResponse
from django.shortcuts import render
from django.views import View
from django.contrib import messages
from flask import current_app
from sklearn import compose
from .models import Upload_Singer, Upload_Songs
from register.models import Upload_Singer, Upload_Songs, Upload_Composer
from .forms import addcomposer_Form, register_Form,  changeUser_Form,addsinger_Form,addsong_Form
from django.contrib.auth import authenticate, login,logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

# Create your views here.
def login_user(request):
    if request.method =="POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        try:
            user = authenticate(request,username=User.objects.get(username=email),password=password)
        except:
            user = authenticate(request,username=username,password=password)
        if user is not None:
            login(request,user)
            return render(request,"register/private.html")
        else:
            messages.success(request,'Đăng nhập thất bại!')
            return render(request, "register/login.html")
    return render(request, "register/login.html",{})


def register(request):
    form = register_Form()
    if request.method =="POST":
        form = register_Form(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request,'Tài khoản '+ user +' đăng ký thành công !')
            return render(request, 'register/register.html')
    
    context = {'form':form}
    return render(request, 'register/register.html',context)
    
def random():
    value = randint(1,9999999)
    return value

@login_required(login_url='/register/login/')
def delete_song(request,event_id):
    current_user = request.user
    event = Upload_Songs.objects.get(id=event_id)
    event.delete()
    upload_songs= Upload_Songs.objects.all().filter(user=current_user)
    return render(request, 'register/private_song.html',{'upload_song': upload_songs})

@login_required(login_url='/register/login/')
def delete_singer(request,event_id):
    current_user = request.user
    event = Upload_Singer.objects.get(id=event_id)
    event.delete()
    upload_singer=Upload_Singer.objects.all().filter(user=current_user)
    return render(request, 'register/private_singer.html',{'upload_singer': upload_singer})
    
@login_required(login_url='/register/login/')
def delete_composer(request,event_id):
    current_user = request.user
    event = Upload_Composer.objects.get(id=event_id)
    event.delete()
    upload_composer=Upload_Composer.objects.all().filter(user=current_user)
    return render(request, 'register/private_composer.html',{'upload_composer': upload_composer})

@login_required(login_url='/register/login/')
def change_user(request):
    if request.method =="POST":
        username = request.POST.get("username")
        first_name = request.POST.get("first_name")
        last_name = request.POST.get("last_name")
        email = request.POST.get("email")
        current_user = request.user
        b = User.objects.get(id=current_user.id)
        User.objects.all().update(first_name=first_name, last_name=last_name, email=email)
        if b is not None:
            messages.success(request,'Thay đổi thông tin thành công!')
            return render(request,"register/change_user.html")
        else:
            messages.success(request,'Thay đổi thông tin thất bại!')
            return render(request, "register/change_user.html")
    return render(request, "register/change_user.html")

@login_required(login_url='/register/login/')
def add_composer(request):
    if request.method =="POST":
        name = request.POST.get("name")
        real_name = request.POST.get("real_name")
        details = request.POST.get("details")
        image = request.FILES['image']
        id=random()
        current_user = request.user
        composer = Upload_Composer(id=id,name=name,image=image,real_name=real_name,details=details,user=current_user)
        if composer is not None:
            composer.save()
            messages.success(request,'Thêm nhạc sĩ ' +name+' thành công!')
            return render(request,"register/add_composer.html")
        else:
            messages.success(request,'Thêm nhạc sĩ thất bại!')
            return render(request, "register/add_composer.html")
    return render(request, "register/add_composer.html")

@login_required(login_url='/register/login/')
def add_singer(request):
    if request.method =="POST":
        name = request.POST.get("name")
        real_name = request.POST.get("real_name")
        image = request.FILES['image']
        details = request.POST.get("details")
        id=random()
        current_user = request.user
        singer = Upload_Singer(id=id,name=name,real_name=real_name,image=image,details=details,user=current_user)
        if singer is not None:
            singer.save()
            messages.success(request,'Thêm ca sĩ ' +name+' thành công!')
            return render(request,"register/add_singer.html")
        else:
            messages.success(request,'Thêm ca sĩ ' +name+' thất bại!')
            return render(request, "register/add_singer.html")
    return render(request, "register/add_singer.html")

@login_required(login_url='/register/login/')
def add_song(request):
    list_composer = Upload_Composer.objects.all()
    list_singer = Upload_Singer.objects.all()
    if request.method =="POST":
        name = request.POST.get("name")
        file = request.FILES['file']
        singer = request.POST.get("singer")
        composer = request.POST.get("composer")
        details = request.POST.get("details")
        upsinger = Upload_Singer.objects.get(id=singer)
        upcomposer = Upload_Composer.objects.get(id=composer)
        current_user = request.user
        id =random()
        song = Upload_Songs.objects.create(id=random(),name=name,file=file,singer=upsinger,composer=upcomposer,details=details,user=current_user)
        if song is not None:
            messages.success(request,'Thêm bài hát ' +name+' thành công!')
            return render(request,"register/add_song.html")
        else:
            messages.success(request,'Thêm bài hát ' +name+' thất bại!')
            return render(request, "register/add_song.html")
    return render(request, "register/add_song.html",{'list_composer':list_composer, 'list_singer': list_singer})

@login_required(login_url='/register/login/')
def logout_user(request):
    logout(request)
    return render(request, 'home/index.html')

class private(LoginRequiredMixin, View):
    login_url = '/'
    def get(self, request):
        current_user = request.user
        return render(request, 'register/private.html',{'current_user': current_user})

class private_song(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        current_user = request.user
        upload_song = Upload_Songs.objects.all().filter(user=current_user)
        return render(request, 'register/private_song.html',{'upload_song': upload_song})

class private_singer(LoginRequiredMixin, View):
    login_url = '/'
    def get(self, request):
        current_user = request.user
        upload_singer = Upload_Singer.objects.all().filter(user=current_user)
        return render(request, 'register/private_singer.html',{'upload_singer': upload_singer})

class private_composer(LoginRequiredMixin, View):
    login_url = '/'

    def get(self, request):
        current_user = request.user
        upload_composer = Upload_Composer.objects.all().filter(user=current_user)
        return render(request, 'register/private_composer.html',{'upload_composer': upload_composer})

register/templates/register/private.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Entro</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <!-- bootstrap css -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'home/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout" style="background-color:rgb(21, 24, 24);">
  <!-- loader  -->
  <!-- header -->
  <header>
    <!-- header inner -->
      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col logo_section">
            </div>
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9">
              
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                        <li class="active"> <a href="{% url 'register:private' %}">Home</a> </li>
                  
                        <li> <a href="{% url 'register:private_song' %}">bài hát</a> </li>
                        <li> <a href="{% url 'register:private_singer' %}">ca sĩ </a> </li>
                        <li> <a href="{% url 'register:private_composer' %}">nhạc sĩ</a> </li>
      
                        <li > <a   href="{% url 'register:logout' %}">đăng xuất</a> </li>
                      <li  > <a  class="last_manu" href="#"><img src="{% static 'home/images/search_icon.png' %}" alt="#" /></a> </li>
                      
                     </ul>
                   </nav>
                
               </div> 
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     
      
    </a>
   </div>
    
  

</section>
</div>
</header>

<button href="#"></button>

<!-- bài hát  -->
<div id="songs" class="about">
  <div class="container">
    <div class="row display_boxflex">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <p>
          <img src="{% static 'composers/images/images1.png'%}">
          <div class="row" >
            <div class="column" >
              <h1>Username:&nbsp; </h1>
            </div>
          <div class="column" >
          <h1>{{ user.username}}</h1>
          </div>
        </div>
        
        <div class="row">
          <div class="column" >
            <h3>Lastname:&nbsp; </h3>
          </div>
          <div class="column" >
            <h3>{{ user.last_name }}</h3>
          </div>
        </div>
          <div class="row">
          <div class="column" >
            <h3>Firstname:&nbsp;  </h3>
          </div>
          <div class="column" >
            <h3>{{ user.first_name }}</h3>
          </div>
        </div>
        <div class="row">
            <div class="column" >
            <h3>Email:&nbsp; </h3>
            </div>
            <div class="column" >
            <h3>{{ user.email}}</h3>
            </div>
          </div>
        </div>
        </p>
          
        </div>
      </div>
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
      </div>
    </div>
    <section class="slider_section">
      <div id="myCarousel" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
          <li data-target="#myCarousel" data-slide-to="1"></li>
          <li data-target="#myCarousel" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
    
            <div class="container">
              <div class="carousel-caption">
                <div class="row">
                  <div class="col-md-12">
                    <div class="text-bg">
                      <a href="{% url 'register:newpassword' %}" class="">Đổi mật khẩu</a> <a href="{% url 'register:change_user' %}" class="">Sửa thông tin </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div>
        </div>
      
    </a>
    </div>
  </div>
</div>
<!-- end abouts -->





</section>

          <!-- Javascript files-->
          <script src="{% static 'home/js/jquery.min.js' %}"></script>
          <script src="{% static 'home/js/popper.min.js' %}"></script>
          <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'home/js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'home/js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'home/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'home/js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>




</body>

</html>

register/templates/register/private_composer.html
<!DOCTYPE html>
<html lang="en">

<head>
  <style>
    .column {
  float: center;
  width: 100%;
  padding: 50px;
  height: 50px;
    }
    img{
      max-width: 250px;
      max-height:250px;

    }
  </style>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Entro</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <!-- bootstrap css -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'home/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout" style="background-color:rgb(21, 24, 24);">
  <!-- loader  -->
  <!-- header -->
  <header>
    <!-- header inner -->
      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col logo_section">
            </div>
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9">
              
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li > <a href="{% url 'register:private' %}">Home</a> </li>
                  
                      <li > <a href="{% url 'register:private_song' %}">bài hát</a> </li>
                      <li> <a href="{% url 'register:private_singer' %}">ca sĩ </a> </li>
                      <li class="active"> <a href="{% url 'register:private_composer' %}">nhạc sĩ</a> </li>
      
                        <li > <a   href="{% url 'register:logout' %}">đăng xuất</a> </li>
                      <li  > <a  class="last_manu" href="#"><img src="{% static 'home/images/search_icon.png' %}" alt="#" /></a> </li>
                      
                     </ul>
                   </nav>
                
               </div> 
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     
     
    </a>
   </div>


</section>
</div>
</header>
    
<button href="#"></button>


<!-- bài hát  -->

<!-- end abouts -->
<div id="songs" class="about">
  <div class="container">
    <div class="row display_boxflex">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="about-box">
          <h2> NHẠC SĨ MỚI</h2>
          <a href="{% url 'register:add_composer' %}">thêm</a>
          {% for item in upload_composer %}
        
          <div >
              <div class = "about">
                <h3> Tên : {{item.name}}  </h3>
                <p> Tên thật : {{item.real_name}} </p>
                <p>  Mô tả : {{item.details}} </p>
                <p> <img src="{{item.image.url}}" alt="" width="50%"> </p>
                <form action="{% url 'register:delete_composer' item.id %}" method="POST">
                  {% csrf_token %}
                  <button type="submit" name="delete">xóa</button>
                  </form>
            {% endfor %}
          </div>
        </div>
        
      </div>
      
      

  </div>
</div>


          <!-- Javascript files-->
          <script src="{% static 'home/js/jquery.min.js' %}"></script>
          <script src="{% static 'home/js/popper.min.js' %}"></script>
          <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'home/js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'home/js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'home/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'home/js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>




</body>

</html>

register/templates/register/private_singer.html
<!DOCTYPE html>
<html lang="en">

<head>
  <style>
    .column {
  float: center;
  width: 100%;
  padding: 50px;
  height: 50px;
    }
    img{
      max-width: 250px;
      max-height:250px;

    }
  </style>
  <!-- basic -->
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <!-- mobile metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="viewport" content="initial-scale=1, maximum-scale=1">
  <!-- site metas -->
  <title>Entro</title>
  <meta name="keywords" content="">
  <meta name="description" content="">
  <meta name="author" content="">
  <!-- fevicon -->
  <!-- bootstrap css -->
  {% load static %}
  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <!-- style css -->
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">
  <!-- Responsive-->
  <link rel="stylesheet" href="{% static 'home/css/responsive.css' %}">  
  <!-- Scrollbar Custom CSS -->
  <link rel="stylesheet" href="{% static 'home/css/jquery.mCustomScrollbar.min.css' %}">
  <!-- Tweaks for older IEs-->
  <link rel="stylesheet" href="https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
<!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
</head>
<!-- body -->

<body class="main-layout" style="background-color:rgb(21, 24, 24);">
  <!-- loader  -->
  <!-- header -->
  <header>
    <!-- header inner -->
      <div class="header">
        <div class="container">
          <div class="row">
            <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col logo_section">
            </div>
            <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9">
              
               <div class="menu-area">
                <div class="limit-box">
                  <nav class="main-menu ">
                    <ul class="menu-area-main">
                      <li > <a href="{% url 'register:private' %}">Home</a> </li>
                  
                      <li > <a href="{% url 'register:private_song' %}">bài hát</a> </li>
                      <li class="active"> <a href="{% url 'register:private_singer' %}">ca sĩ </a> </li>
                      <li> <a href="{% url 'register:private_composer' %}">nhạc sĩ</a> </li>
      
                        <li > <a   href="{% url 'register:logout' %}">đăng xuất</a> </li>
                      <li  > <a  class="last_manu" href="#"><img src="{% static 'home/images/search_icon.png' %}" alt="#" /></a> </li>
                      
                     </ul>
                   </nav>
                
               </div> 
             </div>
           </div>
         </div>
       </div>
     </div>
     <!-- end header inner -->

     <!-- end header -->
     
     
    </a>
   </div>


</section>
</div>
</header>
    
<button href="#"></button>



<div id="songs" class="about">
  <div class="container">
    <div class="row display_boxflex">
      <div class="col-xl-6 col-lg-6 col-md-6 col-sm-12">
        <div class="about-box">
          <h2> CA SĨ MỚI</h2>
          <a href="{% url 'register:add_singer' %}">thêm</a>
          {% for item in upload_singer %}
              <div class = "about">
                <p> <img src="{{item.image.url}}" alt="" width="50%" height="50%" > </p> <h3>  Tên : {{item.name}}  </h3>
                <P>Tên thật : {{item.real_name}} </P>
              <p>Mô tả :  {{item.details}} </p>    
              </div>
              <form action="{% url 'register:delete_singer' item.id %}" method="POST">
                {% csrf_token %}
                <button type="submit" name="delete">xóa</button>
                </form>
                
            {% endfor %}
        </div>
      </div>
      
      
    </div>

  </div>
</div>
<!-- end abouts -->


          <!-- Javascript files-->
          <script src="{% static 'home/js/jquery.min.js' %}"></script>
          <script src="{% static 'home/js/popper.min.js' %}"></script>
          <script src="{% static 'home/js/bootstrap.bundle.min.js' %}"></script>
          <script src="{% static 'home/js/jquery-3.0.0.min.js' %}"></script>
          <script src="{% static 'home/js/plugin.js' %}"></script>
          <!-- sidebar -->
          <script src="{% static 'home/js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
          <script src="{% static 'home/js/custom.js' %}"></script>
          <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>




</body>

</html>